"""
This question is asked by Google. You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. Return the letter that was randomly added to t if it exists, otherwise, return ’ ‘.
Note: You may assume that at most one additional character can be added to t.

Ex: Given the following strings...

    s = "foobar", t = "barfoot", return 't'
    s = "ide", t = "idea", return 'a'
    s = "coding", t "ingcod", return ''
"""
# Time O(s + t) 
# Space O(s)
def spot_the_diff(s, t):
    char_track = {}

    for el in s:
        if el not in char_track:
            char_track[el] = 1
        else:
            char_track[el] += 1
    
    for el in t:
        if el not in char_track:
            return el
        else:
            char_track[el] -= 1

            if char_track[el] < 0:
                return el

    return ''

print(spot_the_diff("foobar", "barfoot"))
print(spot_the_diff("ide", "idea"))
print(spot_the_diff("coding", "ingcod"))

# Time O(s + t)
# Space O(1)
def spot_the_diff(s, t):
    result = 0
    
    for el in s:
        result ^= ord(el)
    
    for el in t:
        result ^= ord(el)
    
    return chr(result)

print(spot_the_diff("foobar", "barfoot"))
print(spot_the_diff("ide", "idea"))
print(spot_the_diff("coding", "ingcod"))